### PR TITLE
Make build.sh executable

### PR DESCRIPTION
**Pull request by troydai**

### CODE REVIEW

**Comment by troydai** [comment]
do we even need this file for this repo?

**Comment by Eilon** [comment]
@ajaybhargavb @pranavkm any idea if this is even needed? The build for DnxTools is presumably somewhat different from other builds...

**Comment by troydai** [comment]
ping @pranavkm @ajaybhargavb

**Comment by pranavkm** [comment]
Yeah, we don't necessarily care about building this in xplat (as yet).

**Comment by troydai** [comment]
ok. I'll close this for now.

**Pull request closed without merging**
