### PR TITLE
Add AppVeyor, Travis build status

### PR DESCRIPTION
**Pull request by hishamco**

### CODE REVIEW

**Comment by hishamco** [comment]
@Eilon please check if AppVeyor is set up for this repo and provide me with AppVeyor token before someone merge this PR

**Comment by Eilon** [comment]
Token: `4apmcfsiatwg8s00`

**Comment by hishamco** [comment]
thanks @Eilon

**Comment by Eilon** [comment]
I just enabled Travis on this repo too.

**Comment by hishamco** [comment]
thanks again for your cooperation

**Comment by Eilon** [comment]
No problem, but thank *you*! :smile:

**Pull request merged**
